package com.david.openassistant.agent

import java.util.Locale

/**
 * A request-specific investigation model generated by the selected reasoning
 * model before deterministic discovery begins.
 */
internal data class AdaptiveResearchQuery(
    val query: String,
    val purpose: String,
    val expectedEvidence: String,
    val dependsOnDiscovery: String?,
    val intent: ResearchSearchIntent? = null,
)

internal data class ResearchSearchIntent(
    val entities: List<String>,
    val geographicScope: String?,
    val metric: String?,
    val timeScope: String?,
    val comparisonClass: String?,
    val unresolvedFact: String,
    val requiredSourceRole: ResearchPassRole,
)

internal data class ValidatedResearchQuery(
    val executionText: String,
    val canonicalFingerprint: String,
    val intent: ResearchSearchIntent,
)

internal data class AdaptiveResearchStrategy(
    val interpretation: String,
    val decisionTarget: String,
    val scopeAmbiguities: List<String>,
    val unknowns: List<String>,
    val evidenceTargets: List<String>,
    val falsifiers: List<String>,
    val followUpRule: String,
    val queries: List<AdaptiveResearchQuery>,
)

/**
 * Last-resort investigation plan used only after two provider serialization
 * attempts fail. Derives a compact entity/topic anchor before composing
 * concise, non-repetitive fallback queries. Strips criteria/instruction boilerplate.
 */
internal fun buildRequestSpecificStrategyFallback(
    goal: AgentGoal,
    task: AgentTask,
    role: ResearchPassRole,
    minimumQueries: Int,
): AdaptiveResearchStrategy {
    require(minimumQueries >= 2)
    val request = goal.userRequest.replace(Regex("\\s+"), " ").trim().take(1_000)
    require(request.isNotBlank()) { "A request-specific research fallback requires the original request." }

    val requestAnchor = extractCompactAnchor(request)

    val criterionAngles = task.acceptanceCriteria.map { stripBoilerplate(it.description) }
    val instructionAngles = task.instructions.split(Regex("(?<=[.!?;])\\s+|\\n+"))
        .filter { it.length >= 10 }
        .map { stripBoilerplate(it) }

    val roleAngles = when (role) {
        ResearchPassRole.DISCOVERY -> listOf(
            "official documentation overview",
            "specifications datasheets",
            "community discussions",
        )
        ResearchPassRole.PRIMARY -> listOf(
            "official records dataset",
            "first-party manual datasheet",
            "authoritative geodetic record",
        )
        ResearchPassRole.CONTRADICTION -> listOf(
            "limitations conflicting reports",
            "discrepancies alternative findings",
        )
        ResearchPassRole.GAP_CLOSURE -> listOf(
            "unresolved specific measurements",
            "citations current status",
        )
        ResearchPassRole.FORENSIC -> listOf(
            "historical records citations",
            "indirect evidence standards",
        )
        else -> listOf(
            "authoritative evidence record",
            "primary documentation",
        )
    }

    val focuses = mutableListOf<String>()
    focuses.addAll(criterionAngles)
    focuses.addAll(instructionAngles)
    focuses.addAll(roleAngles)
    focuses.add(stripBoilerplate(task.title))

    val distinctFocuses = focuses
        .map { it.replace(Regex("\\s+"), " ").trim().take(150) }
        .filter { it.isNotBlank() && it.lowercase(Locale.US) !in BOILERPLATE_PHRASES }
        .distinctBy { it.lowercase(Locale.US) }
        .toMutableList()

    var suffix = 1
    while (distinctFocuses.size < minimumQueries) {
        distinctFocuses.add("unresolved fact $suffix")
        suffix += 1
    }

    val selectedFocuses = distinctFocuses.take(minimumQueries)
    val seenNormalizedQueries = mutableSetOf<String>()

    val queries = mutableListOf<AdaptiveResearchQuery>()
    for ((index, focus) in selectedFocuses.withIndex()) {
        val rawQuery = "$requestAnchor $focus".trim()
        val intent = ResearchSearchIntent(
            entities = extractEntities(rawQuery),
            geographicScope = null,
            metric = null,
            timeScope = null,
            comparisonClass = null,
            unresolvedFact = focus,
            requiredSourceRole = role
        )

        var validation = SearchQueryValidator.validate(rawQuery, request, goal.resolvedResearchRequest, role.name, focus)
        if (validation is SearchQueryValidator.ValidationResult.Rejected || normalizedQueryIn(validation, seenNormalizedQueries)) {
            val compactFocus = focus.split(" ").take(3).joinToString(" ")
            val altRaw = "$requestAnchor $compactFocus".trim()
            validation = SearchQueryValidator.validate(altRaw, request, goal.resolvedResearchRequest, role.name, focus)
        }

        val validQuery = when (validation) {
            is SearchQueryValidator.ValidationResult.Valid -> {
                if (seenNormalizedQueries.add(validation.canonicalFingerprint)) {
                    ValidatedResearchQuery(validation.executionText, validation.canonicalFingerprint, intent)
                } else null
            }
            else -> null
        } ?: continue

        queries.add(
            AdaptiveResearchQuery(
                query = validQuery.executionText,
                purpose = "Resolve information need ${index + 1}: $focus".take(1_000),
                expectedEvidence = "Attributable source material confirming: $focus".take(1_000),
                dependsOnDiscovery = if (index == 0) null else "Refine specific facts from earlier findings.",
                intent = intent
            )
        )
    }

    return AdaptiveResearchStrategy(
        interpretation = "Investigate request with concrete constraints: $request".take(2_000),
        decisionTarget = "Produce evidence for milestone '${task.title}': ${goal.finalOutputDescription}".take(2_000),
        scopeAmbiguities = listOf("Resolve ambiguous terms/dates in: $request"),
        unknowns = selectedFocuses,
        evidenceTargets = selectedFocuses.map { "Evidence for: $it" },
        falsifiers = listOf("Reliable source contradicts constraint in: $request"),
        followUpRule = "Follow evidence trail directly to primary official sources.",
        queries = queries,
    )
}

private fun normalizedQueryIn(validation: SearchQueryValidator.ValidationResult, seen: Set<String>): Boolean {
    return validation is SearchQueryValidator.ValidationResult.Valid && validation.canonicalFingerprint in seen
}

internal fun extractEntities(text: String): List<String> {
    return text.split(Regex("[^\\p{L}\\p{N}+#.-]+"))
        .asSequence()
        .map(String::trim)
        .filter { token ->
            token.length >= 2 &&
                (Character.isUpperCase(token[0]) || token.any { Character.isDigit(it) }) &&
                token.lowercase(Locale.US) !in RESEARCH_QUERY_STOP_WORDS &&
                token.lowercase(Locale.US) !in BOILERPLATE_WORDS
        }
        .distinctBy { it.lowercase(Locale.US) }
        .toList()
}

internal fun requestAnchorTokens(request: String): List<String> {
    return requestAnchorTokens(request, emptyList())
}

internal fun requestAnchorTokens(request: String, taskInstructions: List<String>): List<String> {
    val entities = extractEntities(request)
    
    val tokens = (listOf(request) + taskInstructions).joinToString(" ")
        .split(Regex("[^\\p{L}\\p{N}+#.-]+"))
        .asSequence()
        .map(String::trim)
        .filter { token ->
            val low = token.lowercase(Locale.US)
            (token.length >= 3 && low !in RESEARCH_QUERY_STOP_WORDS && low !in BOILERPLATE_WORDS)
        }
        .distinctBy { it.lowercase(Locale.US) }
        .toMutableList()

    val result = mutableListOf<String>()
    result.addAll(entities)
    result.addAll(tokens.filterNot { t -> 
        entities.any { it.equals(t, ignoreCase = true) } 
    })
    
    return result.distinctBy { it.lowercase(Locale.US) }.take(10)
}

internal fun requestSpecificMaterialAnchorsRequest(
    request: String,
    material: String,
    minimumMatches: Int = 1,
): Boolean {
    val anchors = requestAnchorTokens(request)
    if (anchors.isEmpty()) return true
    val lowerMaterial = material.lowercase(Locale.US)
    val matches = anchors.count { anchor -> lowerMaterial.contains(anchor.lowercase(Locale.US)) }
    return matches >= minimumMatches
}

internal fun adaptiveResearchStrategyAnchorsRequest(
    strategy: AdaptiveResearchStrategy,
    request: String,
    anchors: List<String> = emptyList()
): Boolean {
    val queryText = strategy.queries.joinToString(" ") { it.query }
    if (requestSpecificMaterialAnchorsRequest(request, queryText, minimumMatches = 1)) return true
    
    if (anchors.isNotEmpty()) {
        val lowerQueryText = queryText.lowercase(Locale.US)
        if (anchors.any { anchor -> lowerQueryText.contains(anchor.lowercase(Locale.US)) }) return true
    }
    
    // V41: Loosen anchoring for branches that are explicitly designated as candidate selection
    // or narrow-depth investigations where specific named entities are expected to take over.
    val lowerTarget = strategy.decisionTarget.lowercase(Locale.US)
    val lowerInterp = strategy.interpretation.lowercase(Locale.US)
    if (lowerTarget.contains("candidate") || lowerInterp.contains("candidate") || 
        lowerTarget.contains("named") || lowerInterp.contains("named")) {
        return true
    }
    
    return false
}

internal fun extractCompactAnchor(request: String): String {
    val tokens = requestAnchorTokens(request).take(6)
    return if (tokens.isNotEmpty()) tokens.joinToString(" ") else request.take(100)
}

internal fun stripBoilerplate(text: String): String {
    var cleaned = text
    BOILERPLATE_PHRASES.forEach { phrase ->
        cleaned = cleaned.replace(Regex("(?i)\\b" + Regex.escape(phrase) + "\\b"), "")
    }
    cleaned = cleaned
        .replace(Regex("(?i)\\bat least\\s+\\d+\\b"), "")
        .replace(Regex("(?i)\\bno fewer than\\s+\\d+\\b"), "")
        .replace(Regex("(?i)\\bfor each (?:result|entry|claim|source)\\b"), "")
        .replace(Regex("(?i)\\b(?:provide|include|return|produce)\\s+\\d+\\s+(?:results|entries|claims|sources)\\b"), "")
    return cleaned.replace(Regex("\\s+"), " ").trim()
}

internal fun normalizeQueryForComparison(query: String): String {
    return query.lowercase(Locale.US)
        .replace(Regex("[^a-z0-9\\s]"), "")
        .replace(Regex("\\s+"), " ")
        .trim()
}

internal val RESEARCH_QUERY_STOP_WORDS = setOf(
    "a", "an", "the", "and", "or", "for", "from", "with", "that", "this", "what", "which",
    "is", "are", "was", "were", "be", "been", "being", "in", "on", "at", "to", "of", "as", "by",
    "into", "about", "using", "single",
    "find", "search", "research", "evidence", "source", "sources", "query", "question", "official", "primary",
    "tell", "me", "everything", "you", "can", "own", "develop", "include", "your", "think", "might",
)

internal val BOILERPLATE_WORDS = setOf(
    "least", "one", "must", "include", "provide", "obtain", "report",
)

internal val BOILERPLATE_PHRASES = listOf(
    "at least one",
    "must include",
    "provide evidence",
    "the elevation for",
    "exact gps coordinates",
    "official datasheet",
)


